[package]
name = "ash-bootstrap"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", features = ["loaded"] }
ash-window = { version = "0.13.0", optional = true }
thiserror = "2.0.12"
anyhow = "1.0.98"
raw-window-handle = { version = "0.6.2", optional = true }
tracing = { version = "0.1.41", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
window-handle = [
    "raw-window-handle",
    "ash-window"
]

default = ["window-handle"]