[package]
name = "ash-bootstrap"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["loaded"] }
ash-window = { version = "0.13.0" }
thiserror = "2.0.12"
anyhow = "1.0.98"
raw-window-handle = { version = "0.6.2" }
tracing = { version = "0.1.41", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
winit = "0.30.11"

[[test]]
name = "examples"
path = "examples/main.rs"
harness = false

[features]

# Enables vk_khr_portability_subset and adds ENUMERATE_PORTABILITY_KHR to VkInstanceCreateInfoFlags
portability = []

default = []